"""Repository interfaces. Services depend on these, never on DynamoDB/S3 directly."""

from __future__ import annotations

from typing import Any, Protocol

from app.schemas.assets import WatchlistItem
from app.schemas.briefings import Briefing
from app.schemas.investigations import InvestigationEvent, InvestigationRecord
from app.schemas.uploads import UploadRecord
from app.schemas.users import UserRecord


class UserRepository(Protocol):
    def get(self, user_id: str) -> UserRecord | None: ...
    def put(self, user: UserRecord) -> None: ...
    def delete(self, user_id: str) -> None: ...
    def list_briefing_enabled(self) -> list[UserRecord]: ...


class CredentialRepository(Protocol):
    """Local-auth only (development). Cognito owns credentials in AWS."""

    def get(self, email: str) -> dict[str, Any] | None: ...
    def put(self, email: str, data: dict[str, Any]) -> None: ...


class WatchlistRepository(Protocol):
    def list(self, user_id: str) -> list[WatchlistItem]: ...
    def put(self, item: WatchlistItem) -> None: ...
    def delete(self, user_id: str, symbol: str) -> bool: ...
    def delete_all(self, user_id: str) -> None: ...


class InvestigationRepository(Protocol):
    def get(self, investigation_id: str) -> InvestigationRecord | None: ...
    def put(self, record: InvestigationRecord) -> None: ...
    def list_by_user(self, user_id: str, limit: int = 20) -> list[InvestigationRecord]: ...
    def delete(self, investigation_id: str) -> None: ...


class EventRepository(Protocol):
    def append(self, event: InvestigationEvent) -> InvestigationEvent: ...
    def list_after(self, investigation_id: str, after_seq: int = 0) -> list[InvestigationEvent]: ...
    def delete_for(self, investigation_id: str) -> None: ...


class BriefingRepository(Protocol):
    def get(self, briefing_id: str) -> Briefing | None: ...
    def put(self, briefing: Briefing) -> None: ...
    def list_by_user(self, user_id: str, limit: int = 20) -> list[Briefing]: ...
    def delete(self, briefing_id: str) -> None: ...


class DeliveryRepository(Protocol):
    def claim(self, key: str, metadata: dict[str, Any]) -> bool:
        """Atomically create the delivery marker. Returns False if it already exists (idempotency)."""
        ...

    def get(self, key: str) -> dict[str, Any] | None: ...
    def update(self, key: str, metadata: dict[str, Any]) -> None: ...
    def release(self, key: str) -> None: ...


class UploadRepository(Protocol):
    def get(self, upload_id: str) -> UploadRecord | None: ...
    def put(self, record: UploadRecord) -> None: ...
    def list_by_user(self, user_id: str) -> list[UploadRecord]: ...
    def delete(self, upload_id: str) -> None: ...


class CacheRepository(Protocol):
    def get(self, key: str) -> Any | None: ...
    def set(self, key: str, value: Any, ttl_seconds: int) -> None: ...


class Repositories:
    """Simple container so services receive all repositories through one dependency."""

    def __init__(
        self,
        *,
        users: UserRepository,
        credentials: CredentialRepository,
        watchlists: WatchlistRepository,
        investigations: InvestigationRepository,
        events: EventRepository,
        briefings: BriefingRepository,
        deliveries: DeliveryRepository,
        uploads: UploadRepository,
        cache: CacheRepository,
    ) -> None:
        self.users = users
        self.credentials = credentials
        self.watchlists = watchlists
        self.investigations = investigations
        self.events = events
        self.briefings = briefings
        self.deliveries = deliveries
        self.uploads = uploads
        self.cache = cache
